name: Docker Image CI

on:
  push:
    branches: 
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag muditp1234/file-upload .
    - name: Push the Docker image
      run: docker push muditp1234/file-upload
    
